version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "3000"
    networks:
      youtoop:
        aliases:
          - backend
    environment:
      - PORT=3000
      - ANALYTICS_ENABLED=true
      - ANALYTICS_CODE=${ANALYTICS_CODE}
      - DATA_PATH=/data
    volumes:
      - ./backend/data:/data
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      youtoop:
        aliases:
          - frontend
networks:
  youtoop:
