version: "3"
services:
    backend:
        build: ./backend
        ports:
            - "3000"
        networks:
            youtoop:
                aliases:
                    - backend
        environment:
            - PORT=3000
            - DATA_PATH=${DATA_PATH}
    frontend:
        build: ./frontend
        ports:
            - "80:80"
        networks:
            youtoop:
                aliases:
                    - frontend
networks:
    youtoop:
